apiVersion: v1
kind: Service
metadata:
  name: dagi-router
  labels:
    app: dagi-router
spec:
  type: {{ .Values.service.type }}
  selector:
    app: dagi-router
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 9100
