nodes:
  - node-1-hetzner-gex44
  - node-2-macbook-m4max

microdao:
  - core-operations
  - daarion-dao
  - developer-hub
  - energy-union
  - greenfood-coop
  - clan-network
  - druid-labs
  - soul-district
  - eonarch-vision

agents:
  - daarwizz
  - helion
  - greenfood
  - clan
  - druid
  - eonarch
  - soul
  - yaromir
  - exor
  - faye
  - helix
  - iris
  - sofia
